  apiVersion: v1
  kind: Service
  metadata:
    name: todo-k8s-svc
  spec:
    selector:
      app: todo-k8s
    ports:
      - protocol: "TCP"
        port: 8080
        targetPort: 8080
    type: NodePort