name: Docker Image CI for GHCR

on: push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribtion: "corretto"

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Build Jar
        run: mvn clean package -DskipTests=true

      - name: Build and Push the Image
        run: |
          docker login --username decodingcloud --password ${{secrets.GHCR_PAT}} ghcr.io
          docker build . --tag ghcr.io/decodingcloud/todo-k8s:latest
          docker push ghcr.io/decodingcloud/todo-k8s:latest
